name: Update package.json version

on:
  pull_request:
    types: [opened]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - run: git config --global user.name 'Eloi Pardo'
      - run: git config --global user.email 'eloipr94@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
